export const GET_ANIME_LIST = 'GET_ANIME';
export const GET_ANIME_BY_SLUG = 'GET_ANIME_BY_SLUG';

export const GET_CART_ANIME = 'GET_CART_ANIME';
export const CLEAR_CART_ANIME = 'CLEAR_CART_ANIME';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const GET_PROFILE = 'GET_PROFILE';